create extension if not exists pgcrypto;

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  student_number text not null unique,
  name text not null,
  grade integer not null,
  class_number integer not null,
  seat_number integer not null
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  display_name text not null,
  role text not null check (role in ('student', 'teacher')),
  student_id bigint unique references public.students(id) on delete cascade
);

create table if not exists public.browser_devices (
  id uuid primary key,
  token_hash text not null unique,
  label text not null,
  student_id bigint references public.students(id) on delete cascade,
  created_at timestamptz not null,
  last_seen_at timestamptz not null
);

create table if not exists public.attendance_records (
  id uuid primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  action text not null check (action in ('check_in', 'check_out', 'absent', 'present')),
  "timestamp" timestamptz not null,
  device_id text not null,
  device_label text not null
);

alter table public.students
  add column if not exists seat_number integer;

with numbered_students as (
  select
    id,
    row_number() over (
      order by grade asc, class_number asc, student_number asc
    ) as next_seat_number
  from public.students
  where seat_number is null
)
update public.students
set seat_number = numbered_students.next_seat_number
from numbered_students
where public.students.id = numbered_students.id;

alter table public.students
  alter column seat_number set not null;

alter table public.attendance_records
  drop constraint if exists attendance_records_action_check;

alter table public.attendance_records
  add constraint attendance_records_action_check
  check (action in ('check_in', 'check_out', 'absent', 'present'));

create table if not exists public.web_sessions (
  token_hash text primary key,
  csrf_token_hash text not null,
  user_id bigint not null references public.users(id) on delete cascade,
  expires_at timestamptz not null
);

create index if not exists idx_devices_student
  on public.browser_devices(student_id);

create index if not exists idx_attendance_student_time
  on public.attendance_records(student_id, "timestamp" desc);

create index if not exists idx_students_seat_number
  on public.students(seat_number, student_number);

create index if not exists idx_sessions_user
  on public.web_sessions(user_id);

alter table public.students enable row level security;
alter table public.users enable row level security;
alter table public.browser_devices enable row level security;
alter table public.attendance_records enable row level security;
alter table public.web_sessions enable row level security;

notify pgrst, 'reload schema';
